version: "3.9"

services:
    dualtarget-redis: 
        container_name: dualtarget-redis
        image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

    dualtarget-database:
        container_name: dualtarget-database
        image: postgres:12
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: dualtarget-database
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: {}