const env = {
    MAINNET: [
        {
            NAME: process.env.BLOCKFROST_NETWORK_NAME_MAINNET,
            BLOCKFROST_RPC_URL: process.env.BLOCKFROST_RPC_URL_MAINNET,
            BLOCKFROST_PROJECT_API_KEY: process.env.BLOCKFROST_PROJECT_API_KEY_MAINNET,
            KOIOS_RPC_URL: process.env.KOIOS_RPC_URL_MAINNET,
            DUALTARGET_CONTRACT_ADDRESS: process.env.DUALTARGET_CONTRACT_ADDRESS_MAINNET,
            DUALTARGET_PAYMENT_ADDRESS: process.env.DUALTARGET_CONTRACT_ADDRESS_MAINNET,
            DUALTARGET_STAKE_ADDRESS: process.env.DUALTARGET_CONTRACT_ADDRESS_MAINNET,
            DUALTARGET_TXHASH: process.env.DUALTARGET_CONTRACT_ADDRESS_MAINNET,
            HADA_POOL_ID: process.env.POOL_ID_MAINNET,
        },
    ],

    PREPROD: [
        {
            NAME: process.env.BLOCKFROST_NETWORK_NAME_PREPROD,
            BLOCKFROST_RPC_URL: process.env.BLOCKFROST_RPC_URL_PREPROD,
            BLOCKFROST_PROJECT_API_KEY: process.env.BLOCKFROST_PROJECT_API_KEY_PREPROD,
            KOIOS_RPC_URL: process.env.KOIOS_RPC_URL_PREPROD,
            DUALTARGET_CONTRACT_ADDRESS: process.env.DUALTARGET_STAKE_ADDRESS_PREPROD,
            DUALTARGET_PAYMENT_ADDRESS: process.env.DUALTARGET_STAKE_ADDRESS_PREPROD,
            DUALTARGET_STAKE_ADDRESS: process.env.DUALTARGET_CONTRACT_ADDRESS_MAINNET,
            DUALTARGET_TX_HASH: process.env.DUALTARGET_CONTRACT_ADDRESS_MAINNET,
            HADA_POOL_ID: process.env.POOL_ID_PREPROD,
        },
    ],
};

export default env;
